#!/bin/sh
#

apk add nginx

chmod +x /tmp/entrypoint

cp -av /tmp/entrypoint /sbin/
cp -av /tmp/nginx.conf /etc/nginx/http.d/default.conf

######

cd /var/www

if [ ! -d /var/www/api ]; then
    ver=`curl -s https://api.github.com/repos/imsyy/DailyHotApi/releases/latest | grep 'tag_name' | cut -d '"' -f 4`
    wget https://github.com/imsyy/DailyHotApi/archive/refs/tags/$ver.tar.gz
    mkdir api && tar -xvf $ver.tar.gz -C ./api --strip-components 1
    rm -f $ver.tar.gz
fi

cd /var/www/api

[ -d node_modules ] || npm i

######

cd /var/www

if [ ! -d /var/www/front-build ]; then
    ver=`curl -s https://api.github.com/repos/imsyy/DailyHot/releases/latest | grep 'tag_name' | cut -d '"' -f 4`
    wget https://github.com/imsyy/DailyHot/archive/refs/tags/$ver.tar.gz
    mkdir front-build && tar -xvf $ver.tar.gz -C ./front-build --strip-components 1
    rm -f $ver.tar.gz
fi

cd /var/www/front-build

sed -i "s|Copyright By|$(date +'%Y')|" src/components/Footer.vue
sed -i 's|"author": "imsyy"|"author": "APP_COPYRIGHT"|' package.json
sed -i 's|"github": "https://github.com/imsyy"|"github": "APP_COPYRIGHT_URL"|' package.json

echo "VITE_GLOBAL_API=/dailyhot/api" >.env
echo "VITE_ICP=APP_ICP" >>.env
echo "VITE_DIR=/dailyhot/" >>.env

[ -d node_modules ] || npm i
[ -d dist ] || npm run build

mv dist /var/www/front
rm -rf /var/www/front-build

######

rm -rf /tmp/*
